/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server_CuckooServer */

#ifndef _Included_server_CuckooServer
#define _Included_server_CuckooServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     server_CuckooServer
 * Method:    run
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_server_CuckooServer_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
