/* DO NOT EDIT THIS FILE - it is machine generated */
#include "CuckooFilter/cuckoo_run.h"
#include "server_CuckooServer.h"
/* Header for class server_CuckooServer */

/*
 * Class:     server_CuckooServer
 * Method:    run
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_server_CuckooServer_run
  (JNIEnv *, jobject){
    // TODO: 写死路径
    run("/Users/mrl/Macbook/JavaProject/jeck/src/main/java/server/input.txt","/Users/mrl/Macbook/JavaProject/jeck/src/main/java/server/output.txt");
 }
