package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/ec2-user/workspace/Corretto8/macos/x64/build/Corretto8Src/installers/mac/tar/corretto-build/buildRoot/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, July 21, 2022 7:27:59 PM GMT
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
  	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
  	 */
  public static final int value = (int)(20L);
}
